import { createContext, useContext, useMemo, useState } from 'react'
import { getCookie, removeCookie, setCookie } from '@/lib/cookies'

export type Language = 'en' | 'uz'

const DEFAULT_LANGUAGE: Language = 'uz'
const LANGUAGE_COOKIE = 'sfera-language'
const COOKIE_MAX_AGE = 60 * 60 * 24 * 365

const translations = {
  en: {
    appName: 'Sfera IT Academy',
    administrator: 'Administrator',
    workspaceAccess: 'Workspace access',
    superAdmin: 'Super administrator',
    admin: 'Administrator',
    manager: 'Manager',
    teacher: 'Teacher',
    finance: 'Finance',
    student: 'Student',
    language: 'Language',
    search: 'Search',
    english: 'English',
    uzbek: 'Uzbek',
    general: 'General',
    academy: 'Academy',
    system: 'System',
    light: 'Light',
    dark: 'Dark',
    dashboard: 'Dashboard',
    tasks: 'Tasks',
    apps: 'Apps',
    chats: 'Chats',
    users: 'Users',
    students: 'Students',
    courses: 'Courses',
    pages: 'Pages',
    auth: 'Auth',
    signIn: 'Sign in',
    signInTwoCol: 'Sign in (2 Col)',
    signUp: 'Sign up',
    createAccount: 'Create account',
    createAccountDescription: 'Enter your details to create a secure account.',
    alreadyHaveAccount: 'Already have an account?',
    confirmPassword: 'Confirm password',
    emailRequired: 'Please enter your email.',
    emailInvalid: 'Please enter a valid email address.',
    passwordRequired: 'Please enter your password.',
    passwordLength: 'Password must be at least 7 characters long.',
    confirmPasswordRequired: 'Please confirm your password.',
    passwordMismatch: "Passwords don't match.",
    creatingAccount: 'Creating account...',
    accountCreated: 'Account created successfully.',
    accountCreateError: 'Could not create the account.',
    forgotPassword: 'Forgot password',
    otp: 'OTP',
    errors: 'Errors',
    unauthorized: 'Unauthorized',
    forbidden: 'Forbidden',
    notFound: 'Not Found',
    internalServerError: 'Internal Server Error',
    maintenanceError: 'Maintenance Error',
    other: 'Other',
    settings: 'Settings',
    profile: 'Profile',
    account: 'Account',
    appearance: 'Appearance',
    notifications: 'Notifications',
    display: 'Display',
    helpCenter: 'Help Center',
    securedByClerk: 'Secured by Clerk',
    loginTagline: 'Learn. Build. Grow.',
    loginWelcome: 'Welcome to your workspace',
    loginSecureAccess: 'Secure access for Sfera IT Academy team members.',
    googleSignIn: 'Continue with Google',
    googleAuthPending: 'Google login is ready for backend OAuth connection.',
    loginTitle: 'Welcome back',
    loginSecureLabel: 'Secure access',
    loginHeadlineBefore: 'Manage your education center',
    loginHeadlineAccent: 'from one place',
    loginHeadlineAfter: 'with confidence.',
    loginFeatureCourses: 'Courses',
    loginFeatureStudents: 'Students',
    loginFeatureReports: 'Reports',
    loginCopyright: 'All rights reserved.',
    loginFooter: 'Professional education management',
    email: 'Email',
    password: 'Password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    forgotPasswordQuestion: 'Forgot password?',
    signInDescription:
      'Enter your email and password below to log into your account.',
    noAccount: "Don't have an account?",
    continueWith: 'Or continue with',
    signingIn: 'Signing in...',
    welcomeBack: 'Welcome back',
    invalidCredentials: 'Email or password is incorrect.',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    agreementPrefix: 'By clicking sign in, you agree to our',
    and: 'and',
    download: 'Download',
    overview: 'Overview',
    analytics: 'Analytics',
    reports: 'Reports',
    notificationsTab: 'Notifications',
    customers: 'Customers',
    products: 'Products',
    totalRevenue: 'Total Revenue',
    subscriptions: 'Subscriptions',
    sales: 'Sales',
    activeNow: 'Active Now',
    fromLastMonth: 'from last month',
    sinceLastHour: 'since last hour',
    recentSales: 'Recent Sales',
    madeSalesThisMonth: 'You made 265 sales this month.',
    academyStudents: 'Students',
    activeStudents: 'Active students',
    totalCourses: 'Total courses',
    activeCoursesCount: 'Active courses',
    totalGroups: 'Total groups',
    totalTeachers: 'Total teachers',
    totalDebt: 'Total debt',
    averageAttendance: 'Average attendance',
    newApplications: 'New applications',
    activeGroups: 'Active groups',
    todaysRevenue: 'Today’s revenue',
    indebtedStudents: 'Students with debt',
    changeFromLastMonth: 'from last month',
    newGroups: 'new groups',
    fromYesterday: 'from yesterday',
    newDebt: 'new debt cases',
    leadsAndAdmissions: 'Leads and admissions',
    newLeads: 'New leads',
    contacted: 'Contacted',
    trialLessons: 'Trial lessons',
    admitted: 'Admitted to a course',
    todaysLearning: 'Today’s learning process',
    todaysLessons: 'Today’s lessons',
    attendance: 'Attendance',
    activeCourses: 'Active courses',
    activeTeachers: 'Active teachers',
    monthlyRevenue: 'Monthly revenue',
    latestActivity: 'Latest activity',
    quickActions: 'Quick actions',
    addStudent: 'Add student',
    addLead: 'Add lead',
    createGroup: 'Create group',
    addPayment: 'Add payment',
    unavailableRoute: 'Module route is not available yet',
    activityJoined: 'joined the Frontend course',
    activityPaid: 'made a payment',
    activityAttendance: 'attendance was recorded',
    activityNewStudent: 'new student joined Frontend Group 2',
    activityNewLead: 'was added as a new lead',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    accessDenied: 'Access denied',
    permissionDenied: 'You do not have permission to view this resource.',
    goBack: 'Go back',
    backToHome: 'Back to dashboard',
    userList: 'User List',
    status: 'Status',
    role: 'Role',
    username: 'Username',
    name: 'Name',
    phoneNumber: 'Phone number',
    manageUsers: 'Manage your users and their roles here.',
    filterUsers: 'Filter users...',
    active: 'Active',
    inactive: 'Inactive',
    invited: 'Invited',
    suspended: 'Suspended',
    noResults: 'No results.',
    noResultsFound: 'No results found.',
    addUser: 'Add User',
    inviteUser: 'Invite User',
    inbox: 'Inbox',
    searchChat: 'Search chat...',
    yourMessages: 'Your messages',
    startChat: 'Send a message to start a chat.',
    sendMessage: 'Send message',
    typeMessage: 'Type your messages...',
    newMessage: 'New message',
    to: 'To:',
    searchPeople: 'Search people...',
    noPeopleFound: 'No people found.',
    chat: 'Chat',
    send: 'Send',
    you: 'You',
    chatTextBox: 'Chat text box',
    applications: 'Applications',
    groups: 'Groups',
    teachers: 'Teachers',
    schedule: 'Schedule',
    support: 'Help',
    dashboardSummary: 'A quick overview of academy activity today',
    revenueTrend: 'Revenue trend during 2026',
    latestChanges: 'Latest changes in the CRM',
    frequentActions: 'Quick access to frequently used CRM actions',
    goToStudents: 'Go to student list',
    goToApplications: 'Go to applications',
    goToGroups: 'Go to groups',
    goToFinance: 'Go to finance',
    comingSoon: 'Coming soon',
    leadConversion: 'Conversion rate by lead stage',
    myGroups: 'My groups',
    myCourse: 'My course',
    myGroup: 'My group',
    mySchedule: 'My schedule',
    myAttendance: 'My attendance',
    myTasks: 'My assignments',
    myGrades: 'My grades',
    myPayments: 'My payments',
    myProfile: 'My profile',
    todayLessons: 'Today’s lessons',
    grades: 'Grades',
    financeDashboard: 'Finance dashboard',
    payments: 'Payments',
    debt: 'Outstanding debt',
    revenueDynamics: 'Revenue trend',
    studentStatistics: 'Student statistics',
    attendanceRate: 'Attendance rate',
    coursePerformance: 'Course performance',
    groupActivity: 'Group activity',
    applicationTrends: 'Application trends',
    paymentStatistics: 'Payment statistics',
    outstandingDebt: 'Outstanding debt',
    teacherPerformance: 'Teacher performance',
    weeklyAcademyActivity: 'Weekly academy activity',
    income: 'Income',
    expenses: 'Expenses',
    collected: 'Collected',
    cash: 'Cash',
    card: 'Card',
    click: 'Click',
    payme: 'Payme',
    bankTransfer: 'Bank transfer',
    pendingAmount: 'Pending',
    activeStudentsSeries: 'Active students',
    newStudentsSeries: 'New students',
    studentsEnrolled: 'Students enrolled',
    averageGrade: 'Average grade',
    group: 'Group',
    teacherLabel: 'Teacher',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    paid: 'Paid',
    partiallyPaid: 'Partially paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    refunded: 'Refunded',
    pending: 'Pending',
    noAnalyticsData: 'No analytics data available yet.',
    view: 'View',
    toggleColumns: 'Show or hide columns',
    executiveOverview: 'Executive overview',
    executiveIntelligence: 'Executive intelligence',
    academyCommandCenter: 'Academy command center',
    academyCommandDescription:
      'Understand performance, risks and next actions from one connected view.',
    dashboardRange: 'Dashboard range',
    quickAction: 'Quick action',
    totalStudents: 'Total students',
    recordedTransactions: 'Recorded transactions',
    debtors: 'debtors',
    academyAttendance: 'Academy attendance',
    acrossActiveStudents: 'Across active students',
    new: 'new',
    nearCapacity: 'near capacity',
    revenueAnalytics: 'Revenue analytics',
    collectedAndPending: 'Collected and pending',
    distributionActual: 'Distribution from actual transactions',
    enrollmentFunnel: 'Enrollment funnel',
    dropOffAdmissions: 'Drop-off by admissions stage',
    studentGrowth: 'Student growth',
    activeStudentTrend: 'Active student trend by month',
    studentsAtRisk: 'Students at risk',
    calculatedRisk: 'Calculated from attendance, grade, progress and debt',
    risk: 'Risk',
    groupCapacity: 'Group capacity',
    availableSeats: 'Available seats and operational pressure',
    seatsLeft: 'seats left',
    operationalAttention: 'Operational attention',
    openSourceRecord: 'Open the source record and take action',
    academicReview: 'students need academic review',
    applicationsFollowup: 'applications need follow-up',
    studentsOutstandingDebt: 'students have outstanding debt',
    high: 'High',
    medium: 'Medium',
    recentActivity: 'Recent activity',
    transparentAuditTrail: 'Transparent audit trail',
    upcomingLessons: 'Upcoming lessons',
    scheduleConnectedGroups: 'Schedule connected to groups',
    today: 'Today',
    thisMonth: 'This month',
    thisQuarter: 'This quarter',
    thisYear: 'This year',
    collectedPending: 'Collected and pending',
    notAvailable: 'Not available',
    contactedStage: 'Contacted',
    trialLessonStage: 'Trial lesson',
    approvedStage: 'Approved',
    groupAssignedStage: 'Group assigned',
    enrolledStage: 'Enrolled',
    activeStudentStage: 'Active student',
    growthVsLastMonth: '+12% vs last month',
    backlog: 'Backlog',
    todo: 'To do',
    inProgress: 'In progress',
    done: 'Done',
    canceled: 'Canceled',
  },
  uz: {
    appName: 'Sfera IT Academy',
    administrator: 'Bosh administrator',
    workspaceAccess: 'Tizimga kirish',
    superAdmin: 'Bosh administrator',
    admin: 'Administrator',
    manager: 'Menejer',
    teacher: 'O‘qituvchi',
    finance: 'Moliya',
    student: 'O‘quvchi',
    language: 'Til',
    search: 'Qidirish',
    english: 'Ingliz',
    uzbek: 'O‘zbek',
    general: 'Asosiy',
    academy: 'Akademiya',
    system: 'Tizim',
    light: 'Yorug‘',
    dark: 'Qorong‘i',
    dashboard: 'Boshqaruv paneli',
    tasks: 'Vazifalar',
    apps: 'Ilovalar',
    chats: 'Chatlar',
    users: 'Foydalanuvchilar',
    students: 'O‘quvchilar',
    courses: 'Kurslar',
    pages: 'Sahifalar',
    auth: 'Autentifikatsiya',
    signIn: 'Kirish',
    signInTwoCol: 'Kirish (2 ustun)',
    signUp: 'Ro‘yxatdan o‘tish',
    createAccount: 'Hisob yaratish',
    createAccountDescription:
      'Xavfsiz hisob yaratish uchun ma’lumotlaringizni kiriting.',
    alreadyHaveAccount: 'Hisobingiz bormi?',
    confirmPassword: 'Parolni tasdiqlang',
    emailRequired: 'Elektron pochtangizni kiriting.',
    emailInvalid: 'To‘g‘ri elektron pochta manzilini kiriting.',
    passwordRequired: 'Parolingizni kiriting.',
    passwordLength: 'Parol kamida 7 ta belgidan iborat bo‘lishi kerak.',
    confirmPasswordRequired: 'Parolni tasdiqlang.',
    passwordMismatch: 'Parollar mos kelmadi.',
    creatingAccount: 'Hisob yaratilmoqda...',
    accountCreated: 'Hisob muvaffaqiyatli yaratildi.',
    accountCreateError: 'Hisobni yaratib bo‘lmadi.',
    forgotPassword: 'Parolni unutdingizmi',
    otp: 'Bir martalik kod',
    errors: 'Xatolar',
    unauthorized: 'Ruxsat berilmagan',
    forbidden: 'Taqiqlangan',
    notFound: 'Topilmadi',
    internalServerError: 'Ichki server xatosi',
    maintenanceError: 'Texnik xizmat xatosi',
    other: 'Boshqa',
    settings: 'Sozlamalar',
    profile: 'Profil',
    account: 'Hisob',
    appearance: 'Ko‘rinish',
    notifications: 'Bildirishnomalar',
    display: 'Ekran',
    helpCenter: 'Yordam markazi',
    securedByClerk: 'Clerk orqali himoyalangan',
    loginTagline: 'O‘rganing. Yarating. Rivojlaning.',
    loginWelcome: 'Ish maydoningizga xush kelibsiz',
    loginSecureAccess:
      'Sfera IT Academy jamoasi a’zolari uchun xavfsiz kirish.',
    googleSignIn: 'Google orqali kirish',
    googleAuthPending:
      'Google orqali kirish backend OAuth ulanishini kutmoqda.',
    loginTitle: 'Xush kelibsiz!',
    loginSecureLabel: 'Xavfsiz kirish',
    loginHeadlineBefore: 'Ta’lim markazingizni',
    loginHeadlineAccent: 'bir joydan',
    loginHeadlineAfter: 'ishonch bilan boshqaring.',
    loginFeatureCourses: 'Kurslar',
    loginFeatureStudents: 'O‘quvchilar',
    loginFeatureReports: 'Hisobotlar',
    loginCopyright: 'Barcha huquqlar himoyalangan.',
    loginFooter: 'Professional ta’lim boshqaruvi',
    email: 'Gmail manzili',
    password: 'Parol',
    showPassword: 'Parolni ko‘rsatish',
    hidePassword: 'Parolni yashirish',
    forgotPasswordQuestion: 'Parolni unutdingizmi?',
    signInDescription:
      'Hisobingizga kirish uchun Gmail manzilingiz va parolingizni kiriting.',
    noAccount: 'Hisobingiz yo‘qmi?',
    continueWith: 'Yoki quyidagilardan foydalaning',
    signingIn: 'Kirilmoqda...',
    welcomeBack: 'Xush kelibsiz',
    invalidCredentials: 'Gmail yoki parol noto‘g‘ri.',
    terms: 'Foydalanish shartlari',
    privacy: 'Maxfiylik siyosati',
    agreementPrefix:
      'Kirish tugmasini bosish orqali siz quyidagilarga rozilik bildirasiz:',
    and: 'va',
    download: 'Yuklab olish',
    overview: 'Umumiy ko‘rinish',
    analytics: 'Tahlil',
    reports: 'Hisobotlar',
    notificationsTab: 'Bildirishnomalar',
    customers: 'Mijozlar',
    products: 'Mahsulotlar',
    totalRevenue: 'Jami daromad',
    subscriptions: 'Obunalar',
    sales: 'Savdolar',
    activeNow: 'Hozir faol',
    fromLastMonth: 'o‘tgan oyga nisbatan',
    sinceLastHour: 'oxirgi soatdan beri',
    recentSales: 'So‘nggi savdolar',
    madeSalesThisMonth: 'Bu oyda 265 ta savdo amalga oshirildi.',
    academyStudents: 'Jami o‘quvchilar',
    activeStudents: 'Faol o‘quvchilar',
    totalCourses: 'Jami kurslar',
    activeCoursesCount: 'Faol kurslar',
    totalGroups: 'Jami guruhlar',
    totalTeachers: 'Jami o‘qituvchilar',
    totalDebt: 'Jami qarzdorlik',
    averageAttendance: 'O‘rtacha davomat',
    newApplications: 'Yangi arizalar',
    activeGroups: 'Faol guruhlar',
    todaysRevenue: 'Bugungi tushum',
    indebtedStudents: 'Qarzdor o‘quvchilar',
    changeFromLastMonth: 'o‘tgan oyga nisbatan',
    newGroups: 'yangi guruh',
    fromYesterday: 'kechagi kunga nisbatan',
    newDebt: 'yangi qarzdorlik',
    leadsAndAdmissions: 'Murojaatlar va qabul',
    newLeads: 'Yangi murojaatlar',
    contacted: 'Bog‘lanilganlar',
    trialLessons: 'Trial darsga yozilganlar',
    admitted: 'Kursga qabul qilinganlar',
    todaysLearning: 'Bugungi o‘quv jarayoni',
    todaysLessons: 'Bugungi darslar',
    attendance: 'Bugungi davomat',
    activeCourses: 'Faol kurslar',
    activeTeachers: 'Faol o‘qituvchilar',
    monthlyRevenue: 'Oylik daromad',
    latestActivity: 'So‘nggi faoliyat',
    quickActions: 'Tezkor harakatlar',
    addStudent: 'O‘quvchi qo‘shish',
    addLead: 'Murojaat qo‘shish',
    createGroup: 'Guruh yaratish',
    addPayment: 'To‘lov qo‘shish',
    unavailableRoute: 'Bu modul sahifasi hali ulanmagan',
    activityJoined: 'Frontend kursiga qo‘shildi',
    activityPaid: 'to‘lov qildi',
    activityAttendance: 'davomat holati belgilandi',
    activityNewStudent: 'Frontend 2-guruhga yangi o‘quvchi qo‘shildi',
    activityNewLead: 'yangi murojaat sifatida qo‘shildi',
    minutesAgo: 'daqiqa oldin',
    hoursAgo: 'soat oldin',
    accessDenied: 'Ruxsat berilmadi',
    permissionDenied: 'Sizda bu sahifani ko‘rish uchun yetarli ruxsat yo‘q.',
    goBack: 'Orqaga qaytish',
    backToHome: 'Boshqaruv paneliga qaytish',
    userList: 'O‘quvchilar ro‘yxati',
    status: 'Holati',
    role: 'Roli',
    username: 'Foydalanuvchi nomi',
    name: 'Ism',
    phoneNumber: 'Telefon raqami',
    manageUsers: 'O‘quvchilar va ularning rollarini shu yerda boshqaring.',
    filterUsers: 'O‘quvchini filtrlash...',
    active: 'Faol',
    inactive: 'Faol emas',
    invited: 'Taklif qilingan',
    suspended: 'To‘xtatilgan',
    noResults: 'Natija topilmadi.',
    noResultsFound: 'Hech qanday natija topilmadi.',
    addUser: 'O‘quvchi qo‘shish',
    inviteUser: 'O‘quvchini taklif qilish',
    inbox: 'Chatlar',
    searchChat: 'Chatni qidirish...',
    yourMessages: 'Xabarlaringiz',
    startChat: 'Chatni boshlash uchun xabar yuboring.',
    sendMessage: 'Xabar yuborish',
    typeMessage: 'Xabaringizni yozing...',
    newMessage: 'Yangi xabar',
    to: 'Kimga:',
    searchPeople: 'Odamlarni qidirish...',
    noPeopleFound: 'Hech kim topilmadi.',
    chat: 'Chat',
    send: 'Yuborish',
    you: 'Siz',
    chatTextBox: 'Chat matn maydoni',
    applications: 'Arizalar',
    groups: 'Guruhlar',
    teachers: 'O‘qituvchilar',
    schedule: 'Jadval',
    support: 'Yordam',
    dashboardSummary: 'Akademiya faoliyatining bugungi qisqa ko‘rinishi',
    revenueTrend: '2026-yil davomida tushum dinamikasi',
    latestChanges: 'Tizimdagi eng so‘nggi o‘zgarishlar',
    frequentActions: 'Ko‘p ishlatiladigan amallarga tezkor kirish',
    goToStudents: 'O‘quvchilar ro‘yxatiga o‘tish',
    goToApplications: 'Arizalarga o‘tish',
    goToGroups: 'Guruhlarga o‘tish',
    goToFinance: 'Moliyaga o‘tish',
    comingSoon: 'Tez orada ulanadi',
    leadConversion: 'Murojaat bosqichlari bo‘yicha aylanish ko‘rsatkichi',
    myGroups: 'Mening guruhlarim',
    myCourse: 'Mening kursim',
    myGroup: 'Mening guruhim',
    mySchedule: 'Jadvalim',
    myAttendance: 'Davomatim',
    myTasks: 'Vazifalarim',
    myGrades: 'Baholarim',
    myPayments: 'To‘lovlarim',
    myProfile: 'Profilim',
    todayLessons: 'Bugungi darslar',
    grades: 'Baholar',
    financeDashboard: 'Moliya paneli',
    payments: 'To‘lovlar',
    debt: 'Qarzdorlik',
    revenueDynamics: 'Daromad dinamikasi',
    studentStatistics: 'O‘quvchilar statistikasi',
    attendanceRate: 'Davomat ko‘rsatkichi',
    coursePerformance: 'Kurslar bo‘yicha o‘zlashtirish',
    groupActivity: 'Guruhlar faoliyati',
    applicationTrends: 'Arizalar dinamikasi',
    paymentStatistics: 'To‘lovlar statistikasi',
    outstandingDebt: 'Qarzdorlik',
    teacherPerformance: 'O‘qituvchilar faoliyati',
    weeklyAcademyActivity: 'Haftalik akademiya faoliyati',
    income: 'Tushum',
    expenses: 'Xarajatlar',
    collected: 'Yig‘ilgan',
    cash: 'Naqd',
    card: 'Karta',
    click: 'Click',
    payme: 'Payme',
    bankTransfer: 'Bank o‘tkazmasi',
    pendingAmount: 'Kutilayotgan',
    activeStudentsSeries: 'Faol o‘quvchilar',
    newStudentsSeries: 'Yangi o‘quvchilar',
    studentsEnrolled: 'Ro‘yxatdagi o‘quvchilar',
    averageGrade: 'O‘rtacha baho',
    group: 'Guruh',
    teacherLabel: 'O‘qituvchi',
    present: 'Bor',
    absent: 'Yo‘q',
    late: 'Kechikkan',
    excused: 'Sababli',
    paid: 'To‘langan',
    partiallyPaid: 'Qisman to‘langan',
    unpaid: 'To‘lanmagan',
    overdue: 'Muddati o‘tgan',
    refunded: 'Qaytarilgan',
    pending: 'Kutilmoqda',
    noAnalyticsData: 'Hozircha tahlil ma’lumotlari mavjud emas.',
    view: 'Ko‘rinish',
    toggleColumns: 'Ustunlarni ko‘rsatish yoki yashirish',
    executiveOverview: 'Ijrochi ko‘rinishi',
    executiveIntelligence: 'Ijrochi tahlil',
    academyCommandCenter: 'Akademiya boshqaruv markazi',
    academyCommandDescription:
      'Faoliyat, xavflar va keyingi amallarni yagona bog‘langan ko‘rinishda boshqaring.',
    dashboardRange: 'Dashboard davri',
    quickAction: 'Tezkor amal',
    totalStudents: 'Jami o‘quvchilar',
    recordedTransactions: 'Qayd qilingan tranzaksiyalar',
    debtors: 'qarzdor',
    academyAttendance: 'Akademiya davomati',
    acrossActiveStudents: 'Faol o‘quvchilar bo‘yicha',
    new: 'yangi',
    nearCapacity: 'sig‘imga yaqin',
    revenueAnalytics: 'Tushum tahlili',
    collectedAndPending: 'Yig‘ilgan va kutilayotgan',
    distributionActual: 'Haqiqiy tranzaksiyalar taqsimoti',
    enrollmentFunnel: 'Qabul qilish voronkasi',
    dropOffAdmissions: 'Qabul bosqichlaridagi pasayish',
    studentGrowth: 'O‘quvchilar o‘sishi',
    activeStudentTrend: 'Oylar bo‘yicha faol o‘quvchilar dinamikasi',
    studentsAtRisk: 'E’tibor talab qiladigan o‘quvchilar',
    calculatedRisk: 'Davomat, baho, progress va qarzdorlik asosida hisoblangan',
    risk: 'Xavf',
    groupCapacity: 'Guruhlar sig‘imi',
    availableSeats: 'Bo‘sh joylar va sig‘im holati',
    seatsLeft: 'ta bo‘sh joy',
    operationalAttention: 'E’tibor talab qiladigan masalalar',
    openSourceRecord: 'Asl yozuvga o‘tib, amal bajaring',
    academicReview: 'nafar o‘quvchi akademik ko‘rib chiqishni talab qiladi',
    applicationsFollowup: 'ta ariza aloqa kutilmoqda',
    studentsOutstandingDebt: 'nafar o‘quvchida qarzdorlik bor',
    high: 'Yuqori',
    medium: 'O‘rta',
    recentActivity: 'So‘nggi faoliyat',
    transparentAuditTrail: 'Shaffof audit jurnali',
    upcomingLessons: 'Yaqin darslar',
    scheduleConnectedGroups: 'Guruhlar bilan bog‘langan jadval',
    today: 'Bugun',
    thisMonth: 'Shu oy',
    thisQuarter: 'Shu chorak',
    thisYear: 'Shu yil',
    collectedPending: 'Yig‘ilgan va kutilayotgan',
    notAvailable: 'Mavjud emas',
    contactedStage: 'Bog‘langan',
    trialLessonStage: 'Sinov darsi',
    approvedStage: 'Tasdiqlangan',
    groupAssignedStage: 'Guruh biriktirilgan',
    enrolledStage: 'Qabul qilingan',
    activeStudentStage: 'Faol o‘quvchi',
    growthVsLastMonth: 'O‘tgan oyga nisbatan +12%',
    backlog: 'Rejada',
    todo: 'Bajariladi',
    inProgress: 'Jarayonda',
    done: 'Bajarildi',
    canceled: 'Bekor qilingan',
  },
} as const

export type TranslationKey = keyof typeof translations.en

type LanguageProviderState = {
  language: Language
  setLanguage: (language: Language) => void
  resetLanguage: () => void
  t: (key: TranslationKey) => string
}

const initialState: LanguageProviderState = {
  language: DEFAULT_LANGUAGE,
  setLanguage: () => null,
  resetLanguage: () => null,
  t: (key) => translations[DEFAULT_LANGUAGE][key],
}

const LanguageContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, _setLanguage] = useState<Language>(() => {
    const storedLanguage = getCookie(LANGUAGE_COOKIE)
    return storedLanguage === 'uz' || storedLanguage === 'en'
      ? storedLanguage
      : DEFAULT_LANGUAGE
  })

  const setLanguage = (nextLanguage: Language) => {
    setCookie(LANGUAGE_COOKIE, nextLanguage, COOKIE_MAX_AGE)
    _setLanguage(nextLanguage)
  }

  const resetLanguage = () => {
    removeCookie(LANGUAGE_COOKIE)
    _setLanguage(DEFAULT_LANGUAGE)
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      resetLanguage,
      t: (key: TranslationKey) => translations[language][key],
    }),
    [language]
  )

  return <LanguageContext value={value}>{children}</LanguageContext>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  return useContext(LanguageContext)
}

export function formatCurrency(value: number, language: Language) {
  const locale = language === 'en' ? 'en-US' : 'uz-UZ'
  const suffix = language === 'en' ? ' UZS' : ' so‘m'
  return `${new Intl.NumberFormat(locale).format(value)}${suffix}`
}
